# Generated by Django 4.0 on 2021-12-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product_allergens',
            table='product_allergens',
        ),
    ]
