# Generated by Django 4.0 on 2021-12-12 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_allergens_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_ml', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('size_fluid_ounce', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.RemoveField(
            model_name='allergens',
            name='product',
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sizes'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
