# Generated by Django 4.0 on 2021-12-12 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_sizes_remove_allergens_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionfacts',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sizes'),
        ),
    ]
